Seed database
sky-bnb/component-reviews-bl pull request #1
Opened 2019-05-16 07:45 UTC by bjlagman12

Basic set up for react, webpack, express, and eslint. A chunk of the work you will be reviewing lives in the data.seeding.js file and orm_schema.js file. After you forked and cloned down my repo. Please do the following

`npm install`
`npm run seed-data`

you can confirm in the 'reviews' db that all the data lives there

2019-05-16 18:03 UTC, gregoryinouye commented on server/dbs/data.seed.js
> +  for (let i = 0; i <= 100; i += 1) {
i think we had wanted to use 101 - 200 as the ids for our fake data?

2019-05-16 18:05 UTC, gregoryinouye commented on server/dbs/data.seed.js
> +          review_id: j,
do you want the review_id to be a globally unique review_id or do you want it to be specific to a particular house (e.g. there is only one review 101 in all the records, or each house has a review_id 101)? not sure if this matters.

2019-05-16 18:19 UTC, gregoryinouye requested changes
required change: please change house_id to be within 101-200.

other comments: see other notes

2019-05-16 19:11 UTC, bjlagman12 commented on server/dbs/data.seed.js
> +  for (let i = 0; i <= 100; i += 1) {
Thanks yes i noticed that i can fix that no problem

2019-05-16 19:11 UTC, bjlagman12 commented on server/dbs/data.seed.js
> +          review_id: j,
my review id it depending on the house_id we are in

2019-05-16 20:52 UTC, gregoryinouye approved these changes
looks good, thanks!

2019-05-16 21:30 UTC, merged

2019-05-17 03:49 UTC, gregoryinouye commented on server/dbs/data.seed.js
> +    promise.push(review);
@bjlagman12: instead of adding "review" to the array that you pass into promise.resolve, shouldn't it be review.save()? your code generates the sample review data fine for me, but this format did not work for my seeding script.

https://mongoosejs.com/docs/api.html#model_Model-save

2019-05-17 04:13 UTC, bjlagman12 commented on server/dbs/data.seed.js
> +    promise.push(review);
We can not add the the review.save() into the array because it will only save it once we need to make sure that the review.save is within the for loop that that is save 100 times. The purpose of the promise.resolve is so that after all the data is saved into the db then i will close the connection for the database

2019-05-17 04:25 UTC, gregoryinouye commented on server/dbs/data.seed.js
> +    promise.push(review);
since you are invoking review.save(), you can still save it each time. it just seems that you want to call promise.resolve() on an array of promises, and review.save() returns a Promise, not review itself.

2019-05-18 00:28 UTC, gregoryinouye commented on server/dbs/data.seed.js
> +  // NO NEED TO DROP THE DB BECAUSE IT WILL RESET THE DATA EVERY TIME THE SCRIPT IS RAN
@bjlagman12 i think the database needs to be dropped or the information overwritten - otherwise for each run of the seed script, a new house_id for 101-200 will be created.